# Generated by Django 4.2.6 on 2023-11-04 22:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import libresenses.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('year', models.IntegerField(blank=True, help_text='Insira o ano de lançamento do filme.', null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2023)])),
                ('length', models.IntegerField(blank=True, help_text='Duração do filme em minutos.', null=True)),
                ('rating', models.CharField(blank=True, choices=[('Livre', 'Livre (para todos os públicos)'), ('10', '10 anos'), ('12', '12 anos'), ('14', '14 anos'), ('16', '16 anos'), ('18', '18 anos')], max_length=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('background', models.ImageField(blank=True, help_text='Faça o upload da imagem de fundo nos formatos jpg, jpeg, png, gif ou bmp. Max 2MB.', upload_to=libresenses.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp']), libresenses.models.validate_file_size])),
                ('thumbnail', models.ImageField(blank=True, help_text='Faça o upload da imagem em miniatura nos formatos jpg, jpeg, png, gif ou bmp. Max 2MB.', upload_to=libresenses.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp']), libresenses.models.validate_file_size])),
                ('permalink', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_language_video_url', models.URLField(help_text='URL para o vídeo em língua de sinais.')),
                ('language', models.CharField(max_length=50)),
                ('is_hardcoded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign_languages', to='libresenses.film')),
            ],
        ),
        migrations.CreateModel(
            name='MediaAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative_file', models.FileField(help_text='Faça o upload do arquivo de mídia alternativa. Max 2MB.', upload_to=libresenses.models.get_upload_path, validators=[libresenses.models.validate_file_size])),
                ('language', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_alternatives', to='libresenses.film')),
            ],
        ),
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption_file', models.FileField(blank=True, help_text='Faça o upload do arquivo de legenda nos formatos srt ou vtt. Max 2MB.', upload_to=libresenses.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['srt', 'vtt']), libresenses.models.validate_file_size])),
                ('language', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captions', to='libresenses.film')),
            ],
        ),
        migrations.CreateModel(
            name='AudioDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_url', models.URLField(help_text='URL para a descrição em áudio.')),
                ('language', models.CharField(max_length=50)),
                ('is_extended', models.BooleanField(default=False)),
                ('is_only_audio', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_descriptions', to='libresenses.film')),
            ],
        ),
    ]
