# Generated by Django 4.2.6 on 2023-10-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libresenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caption',
            name='file',
            field=models.FileField(blank=True, upload_to='captions/'),
        ),
        migrations.AlterField(
            model_name='caption',
            name='language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='film',
            name='background',
            field=models.ImageField(blank=True, upload_to='backgrounds/'),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.CharField(blank=True, choices=[('Livre', 'Livre'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('18', '18')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='film',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='film',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
