# Generated by Django 4.2.6 on 2023-11-04 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libresenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiodescription',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='caption',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='mediaalternative',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='signlanguage',
            name='updated_at',
        ),
    ]
