# Generated by Django 4.2.6 on 2023-11-26 23:57

import django.core.validators
from django.db import migrations, models
import libresenses.models


class Migration(migrations.Migration):

    dependencies = [
        ('libresenses', '0002_alter_film_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodescription',
            name='audio_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='audiodescription',
            name='is_extended',
            field=models.BooleanField(default=False, help_text='Adicionada ao conteúdo através de pausas no vídeo.'),
        ),
        migrations.AlterField(
            model_name='audiodescription',
            name='is_only_audio',
            field=models.BooleanField(default=False, help_text='Somente o áudio, sem o vídeo.'),
        ),
        migrations.AlterField(
            model_name='caption',
            name='caption_file',
            field=models.FileField(help_text='Formatos: srt ou vtt.', upload_to=libresenses.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['srt', 'vtt']), libresenses.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='film',
            name='background',
            field=models.ImageField(blank=True, help_text='Formatos: jpg, jpeg, png, gif, bmp.', upload_to=libresenses.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp']), libresenses.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='film',
            name='length',
            field=models.IntegerField(help_text='Duração em minutos.', null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.CharField(choices=[('Livre', 'Livre'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('18', '18')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Formatos: jpg, jpeg, png, gif, bmp.', upload_to=libresenses.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp']), libresenses.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='film',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2023)]),
        ),
        migrations.AlterField(
            model_name='mediaalternative',
            name='alternative_file',
            field=models.FileField(upload_to=libresenses.models.get_upload_path, validators=[libresenses.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='signlanguage',
            name='is_hardcoded',
            field=models.BooleanField(default=False, help_text='Deixe em branco se o vídeo da língua de sinais for separado do filme.'),
        ),
        migrations.AlterField(
            model_name='signlanguage',
            name='sign_language_video_url',
            field=models.URLField(),
        ),
    ]
